language: python
python: 2.7
install: pip install tox
addons:
  apt:
    update: true
matrix:
    include:
      - language: python
        python: 2.7
        env: TOXENV=py27
        before_install:
          - sudo apt-get install -y antlr4
          - cd python
        script: tox
