language: python
python: 2.7
install: pip install tox
dist: bionic

matrix:
  include:
    - language: python
      python: 2.7
      env: TOXENV=py27
      before_install:
        - cd python
      script: tox

    - language: python
      python: 3.6
      env: TOXENV=py36
      before_install:
        - cd python
      script: tox
