language: generic

matrix:
  include:
    - os: osx
    - os: linux

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update
      sudo apt-get install cabal-install
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install ghc cabal-install
    fi
  - cabal update

script: >
  cabal install --only-dependencies --enable-tests &&
  cabal configure --enable-tests &&
  cabal build &&
  cabal test
